Importing Libraries

In [2]:
import pandas as pd
import numpy as np

Load the Data

In [3]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [4]:
data_preprocessed.head()

reason_0  reason_1  reason_2  reason_3  Month_val  Weekday        Date  \
0         0         0         0         1          7        1  2015-07-07   
1         0         0         0         0          7        1  2015-07-14   
2         0         0         0         1          7        2  2015-07-15   
3         1         0         0         0          7        3  2015-07-16   
4         0         0         0         1          7        3  2015-07-23   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

Creating the Targets

In [5]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [6]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [9]:
data_preprocessed['Excessive Absenteeism'] = targets

In [10]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [41]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)

Droppping unnecessary columns

In [42]:
#dropping after checking the coeff of features after training the model
data_with_targets = data_with_targets.drop(['Date', 'Weekday', 'Distance to Work', 'Education'], axis=1)

In [43]:
data_with_targets.head()

reason_0  reason_1  reason_2  reason_3  Month_val  Transportation Expense  \
0         0         0         0         1          7                     289   
1         0         0         0         0          7                     118   
2         0         0         0         1          7                     179   
3         1         0         0         0          7                     279   
4         0         0         0         1          7                     289   

   Age  Daily Work Load Average  Body Mass Index  Children  Pets  \
0   33                  239.554               30         2     1   
1   50                  239.554               31         1     0   
2   38                  239.554               31         0     0   
3   39                  239.554               24         2     0   
4   33                  239.554               30         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [45]:
data_with_targets.shape

(700, 12)

In [46]:
unscaled_inputs = data_with_targets.iloc[:, 0:-1]

In [47]:
unscaled_inputs.head()

reason_0  reason_1  reason_2  reason_3  Month_val  Transportation Expense  \
0         0         0         0         1          7                     289   
1         0         0         0         0          7                     118   
2         0         0         0         1          7                     179   
3         1         0         0         0          7                     279   
4         0         0         0         1          7                     289   

   Age  Daily Work Load Average  Body Mass Index  Children  Pets  
0   33                  239.554               30         2     1  
1   50                  239.554               31         1     0  
2   38                  239.554               31         0     0  
3   39                  239.554               24         2     0  
4   33                  239.554               30         2     1

Standardizing the data

In [48]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [49]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [50]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [51]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.76743118,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ...,  1.00263338,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  1.00263338,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.40857982,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
        -0.01928035,  0.26848661]])

In [52]:
scaled_inputs.shape

(700, 11)

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
train_test_split(scaled_inputs, targets, random_state=2)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -1.11418642,
          0.88046927, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ...,  1.00263338,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ...,  1.00263338,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
         -0.01928035,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
          0.88046927,  1.12666297],
        [ 1.73205081, -0.09298136, -0.31448545, ...,  0.76743118,
          0.88046927,  0.26848661]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.87898422,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.87898422,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ...,  0.76743118,
          0.88046927,  0.26848661],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ...,  

In [55]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=2)

In [56]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(560, 11) (560,)
(140, 11) (140,)


Training the Model using sklearn

In [57]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [58]:
reg = LogisticRegression()

In [59]:
reg.fit(x_train, y_train)

LogisticRegression()

In [60]:
reg.score(x_train, y_train)

0.7732142857142857

Manually cheeck the accuracy

In [61]:
model_output = reg.predict(x_train)

In [62]:
np.sum(model_output == y_train)

433

In [63]:
np.sum(model_output == y_train)/model_output.shape[0]

0.7732142857142857

In [64]:
feature_name = unscaled_inputs.columns.values

In [65]:
summaryTable = pd.DataFrame(columns=['Feature name'], data=feature_name)
summaryTable['Coefficient'] = np.transpose(reg.coef_)
summaryTable

Feature name  Coefficient
0                  reason_0     1.981941
1                  reason_1     0.268978
2                  reason_2     1.582491
3                  reason_3     1.205649
4                 Month_val     0.093132
5    Transportation Expense     0.681197
6                       Age    -0.233396
7   Daily Work Load Average    -0.009989
8           Body Mass Index     0.269222
9                  Children     0.381512
10                     Pets    -0.391741

In [66]:
summaryTable.index = summaryTable.index+1

In [67]:
summaryTable.loc[0] = ['Intercept', reg.intercept_[0]]
summaryTable = summaryTable.sort_index()

In [68]:
summaryTable

Feature name  Coefficient
0                 Intercept    -0.183545
1                  reason_0     1.981941
2                  reason_1     0.268978
3                  reason_2     1.582491
4                  reason_3     1.205649
5                 Month_val     0.093132
6    Transportation Expense     0.681197
7                       Age    -0.233396
8   Daily Work Load Average    -0.009989
9           Body Mass Index     0.269222
10                 Children     0.381512
11                     Pets    -0.391741

Testing the Model

In [69]:
reg.score(x_test, y_test)

0.75

In [70]:
prediction = reg.predict_proba(x_test)

In [71]:
prediction

array([[0.75882395, 0.24117605],
       [0.24294784, 0.75705216],
       [0.07991786, 0.92008214],
       [0.79679891, 0.20320109],
       [0.115786  , 0.884214  ],
       [0.51963007, 0.48036993],
       [0.12478556, 0.87521444],
       [0.32790528, 0.67209472],
       [0.08025831, 0.91974169],
       [0.31119097, 0.68880903],
       [0.1210768 , 0.8789232 ],
       [0.25633712, 0.74366288],
       [0.50986353, 0.49013647],
       [0.38086073, 0.61913927],
       [0.74460208, 0.25539792],
       [0.29708559, 0.70291441],
       [0.78991309, 0.21008691],
       [0.12806932, 0.87193068],
       [0.60911594, 0.39088406],
       [0.7761199 , 0.2238801 ],
       [0.43443189, 0.56556811],
       [0.14553434, 0.85446566],
       [0.13823692, 0.86176308],
       [0.75001821, 0.24998179],
       [0.39286176, 0.60713824],
       [0.35747626, 0.64252374],
       [0.98750304, 0.01249696],
       [0.57436553, 0.42563447],
       [0.55354634, 0.44645366],
       [0.86642126, 0.13357874],
       [0.

In [72]:
absenteeism = prediction[:, 1]
absenteeism

array([0.24117605, 0.75705216, 0.92008214, 0.20320109, 0.884214  ,
       0.48036993, 0.87521444, 0.67209472, 0.91974169, 0.68880903,
       0.8789232 , 0.74366288, 0.49013647, 0.61913927, 0.25539792,
       0.70291441, 0.21008691, 0.87193068, 0.39088406, 0.2238801 ,
       0.56556811, 0.85446566, 0.86176308, 0.24998179, 0.60713824,
       0.64252374, 0.01249696, 0.42563447, 0.44645366, 0.13357874,
       0.05511653, 0.73162914, 0.30933427, 0.21578297, 0.20957211,
       0.63112216, 0.38351129, 0.5820906 , 0.27008091, 0.14176168,
       0.1086292 , 0.77546187, 0.13727077, 0.61981942, 0.86388166,
       0.83086363, 0.96713706, 0.20957211, 0.7194724 , 0.19513557,
       0.73796874, 0.77322137, 0.70070849, 0.40257992, 0.884214  ,
       0.85061011, 0.21008691, 0.33813108, 0.2471741 , 0.15314499,
       0.25539792, 0.57091972, 0.26452051, 0.13095852, 0.21008691,
       0.10474392, 0.64658779, 0.78319094, 0.23195251, 0.26010287,
       0.38720104, 0.30456113, 0.97218719, 0.13203591, 0.11696

Saving the Model

In [73]:
import pickle

In [74]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [75]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)

In [76]:
feature_name

array(['reason_0', 'reason_1', 'reason_2', 'reason_3', 'Month_val',
       'Transportation Expense', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Children', 'Pets'], dtype=object)